---

services:
  nginx:
    image: nginx:alpine
    container_name: absensi_web
    volumes:
      - ./public:/var/www/public:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - frontend
      - backend
    depends_on:
      - php-fpm
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.absensi.rule=Host(`absensi.joppanaditya.my.id`)"
      - "traefik.http.routers.absensi.entrypoints=websecure"
      - "traefik.http.routers.absensi.tls=true"
      - "traefik.http.routers.absensi.tls.certresolver=cloudflare"
      - "traefik.http.routers.absensi.service=absensi-svc"
      - "traefik.http.services.absensi-svc.loadbalancer.server.port=80"

  php-fpm:
    container_name: absensi_php
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www:cached
      - ./storage:/var/www/storage:delegated
      - ./bootstrap/cache:/var/www/bootstrap/cache:delegated
    networks:
      - backend
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: absensi_mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/config/mysql.cnf:/etc/mysql/conf.d/custom.cnf
    networks:
      - backend
    ports:
      - "3306:3306"

  redis:
    image: redis:7-alpine
    container_name: absensi_redis
    networks:
      - backend

networks:
  frontend:
    external: true
  backend:
    external: true
